# Set theme on HA start
  - alias: Set theme at startup
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: frontend.set_theme
      data:
        name: slate
#   - alias: 'Set dark theme for the night'
#     initial_state: True
#     trigger:
#       - platform: time
#         at: '20:00'
#     action:
#       - service: frontend.set_theme
#         data:
#           name: slate