# TODO
#  - Use custom updater instead of hard coding custom components
#  - Improve Cheryl automation, flash lights, use spotify?
#  - Clean up Google Home entities

title: Nichols' Home

resources:
  - url: /local/mini-graph-card-bundle.js?v=0.1.0
    type: module

temp-sensor-defaults: &temp-sensor-defaults
  line_width: 8
  font_size: 80
  line_color: '#3ce77b'
  line_value_above: 23
  line_color_above: '#e74c3c'
  line_value_below: 21
  line_color_below: '#3498db'
  hide:
    - icon

views:
  - path: default_view
    title: Home
    icon: mdi:home
    cards:
      - type: entity-filter
        entities:
          - device_tracker.calvins_phone
          - device_tracker.minahils_phone
          - device_tracker.galaxys8
          - device_tracker.cherylsiphone
        state_filter:
          - home
        card: 
          type: glance
          title: People at home
          show_header_toggle: false
          show_state: false
      - type: entities
        entities:
          - sensor.current_uv_index
          - sensor.max_uv_index
          - sensor.skin_type_3_safe_exposure_time
      - type: entities
        entities:
          - sensor.phone_to_home
          - sensor.home_to_work
        name: Current UV Index
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: map
            aspect_ratio: 16:9
            default_zoom: 25
            entities:
              - device_tracker.google_maps_113354980897491525856
              - zone.home
              - zone.work
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            entity: sensor.my_ecobee_humidity
            line_width: 8
            font_size: 80
            line_color: '#3ce77b'
            line_value_above: 40
            line_color_above: '#e74c3c'
            line_value_below: 30
            line_color_below: '#3498db'
            name: Ecobee Humidity
            hide:
              - icon
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entity: sensor.bedroom_temperature
                name: Bedroom
                <<: *temp-sensor-defaults
              - type: custom:mini-graph-card
                entity: sensor.living_room_temperature
                name: Living Room
                <<: *temp-sensor-defaults
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entity: sensor.office_temperature
                name: Office
                <<: *temp-sensor-defaults
              - type: custom:mini-graph-card
                entity: sensor.kitchen_temperature
                name: Kitchen
                <<: *temp-sensor-defaults
      - type: horizontal-stack
        cards:
          - type: glance
            show_header_toggle: false
            show_name: false
            entities:
            - entity: device_tracker.calvins_phone
              name: Calvin
            - entity: device_tracker.minahils_phone
              name: Minahil
            - entity: device_tracker.galaxys8
      - type: glance
        title: Occupancy
        show_state: false
        entities:
        - entity: binary_sensor.living_room_occupancy
          name: Living Room
        - entity: binary_sensor.kitchen_occupancy
          name: Kitchen
        - entity: binary_sensor.bedroom_occupancy
          name: Master Bedroom
        - entity: binary_sensor.office_occupancy
          name: Office
        image: /local/calvin.jpeg
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.kitchen_sink
          - type: vertical-stack
            cards:
              - type: entity-button
                entity: switch.35808047b4e62d1dc5b3
                show_state: true
                name: Recliner Switch
              - type: entity-button
                entity: switch.3580804784f3eb228212
                show_state: true
                name: Office Switch
  - path: lights
    title: Lighting
    icon: mdi:lightbulb-outline
    cards:
      - title: Light
        type: entities
        entities:
          - light.kitchen
          - light.kitchen_sink
          - light.hallway
          - light.hall_1
          - light.hall_2
          - light.hall_3
          - light.hall_4
  - path: media
    title: Media
    icon: mdi:speaker
    cards:
      - type: media-control
        entity: media_player.bedroom_home
      - type: media-control
        entity: media_player.home_group
      - type: media-control
        entity: media_player.kitchen_home
      - type: media-control
        entity: media_player.office_home
      - type: media-control
        entity: media_player.living_room_home
      - type: media-control
        entity: media_player.living_room_tv
  - path: temperature
    title: Temperature
    icon: 'mdi:thermometer'
    cards:
      - type: thermostat
        entity: climate.my_ecobee
      - type: weather-forecast
        entity: weather.my_ecobee
  - path: settings
    title: Settings
    icon: mdi:alpha-z-box
    cards:
      - title: Z-Wave
        type: entities
        entities:
          - zwave.aeotec_zw090_zstick_gen5_us
